version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB:       pulsedb
      POSTGRES_USER:     pulseuser
      POSTGRES_PASSWORD: pulsepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Auto-run SQL files on first container start
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/triggers.sql:/docker-entrypoint-initdb.d/02_triggers.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/03_seed.sql
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pulseuser -d pulsedb']
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT:         3000
      DATABASE_URL: postgresql://pulseuser:pulsepass@postgres:5432/pulsedb
      REDIS_URL:    redis://redis:6379
      NODE_ENV:     production
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
